[__config__]
oldver = "cur_ver.json"
newver = "new_ver.json"

[passwall]
source = "git"
git = "https://github.com/Openwrt-Passwall/openwrt-passwall"
use_commit = true

[passwall2]
source = "git"
git = "https://github.com/Openwrt-Passwall/openwrt-passwall2"
use_commit = true

[packages]
source = "git"
git = "https://github.com/Openwrt-Passwall/openwrt-passwall-packages"
use_commit = true
