name: Build Test

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target architecture'
        required: true
        default: x86_64

      sdk_version:
        description: 'SDK version'
        required: true
        default: snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build package
        uses: openwrt/gh-action-sdk@master
        env:
          ARCH: ${{ github.event.inputs.arch }}-${{ github.event.inputs.sdk_version }}
          EXTRA_FEEDS: >-
            src-git|passwall_packages|https://github.com/xiaorouji/openwrt-passwall;packages
            src-git|passwall_luci|https://github.com/xiaorouji/openwrt-passwall;luci
            src-git|passwall2|https://github.com/xiaorouji/openwrt-passwall2;main
          KEY_BUILD: ${{ secrets.SIGN_PRIV_KEY }}
          V: s

      - name: Save Build Result
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-passwall
          path: bin/packages/${{ github.event.inputs.arch }}/passwall*/*.ipk
          retention-days: 7
